#ifndef _ballistic_base_h_
#define _ballistic_base_h_

#define BALLISTIC_BASE_EXPORT

#include "ballistic.animation.component.h"
#include "ballistic.animation.function.h"
#include "ballistic.animation.storyboard.h"
#include "ballistic.common_id.h"
#include "ballistic.component_constructor.h"
#include "ballistic.component_container.h"
#include "ballistic.component_info.h"
#include "ballistic.config.h"
#include "ballistic.convert.h"
#include "ballistic.debug.h"
#include "ballistic.entity.h"
#include "ballistic.entity_container.h"
#include "ballistic.entity_type.h"
#include "ballistic.game.h"
#include "ballistic.icomponent.h"
#include "ballistic.id.h"
#include "ballistic.ifrontend.h"
#include "ballistic.io.entity_type_reader.h"
#include "ballistic.io.iloader.h"
#include "ballistic.io.istorage.h"
#include "ballistic.io.package_loader.h"
#include "ballistic.io.package_reader.h"
#include "ballistic.io.storage_filesystem.h"
#include "ballistic.iresource.h"
#include "ballistic.isystem.h"
#include "ballistic.math.aabox.h"
#include "ballistic.math.matrixes.h"
#include "ballistic.math.quat.h"
#include "ballistic.math.rect.h"
#include "ballistic.math.vecn_t.h"
#include "ballistic.math.vectors.h"
#include "ballistic.message.h"
#include "ballistic.message_notifier.h"
#include "ballistic.property.h"
#include "ballistic.property_container.h"
#include "ballistic.res_id.h"
#include "ballistic.resource_container.h"
#include "ballistic.system.h"
#include "ballistic.system_container.h"

#endif